### ISSUE TITLE
pg-analyse requires Python '>=3.6'

### ISSUE THREAD

**Issue by biter777** [idlesign/pg_analyse#1]
Can you tell me what I'm doing wrong?
Thnx
----

$ pip install pg_analyse[cli]
Collecting pg_analyse[cli]
  Downloading https://files.pythonhosted.org/packages/df/a1/49f8057741dbf710f67529a869ff66d1f7ea063d9097dae0821cfdd302e2/pg_analyse-0.3.0-py2.py3-none-any.whl
pg-analyse requires Python '>=3.6' but the running Python is 2.7.17

$ python3 -V
Python 3.7.5

**Comment by idlesign** [comment]
Your distribution probably has `pip3` command to install package for python 3.
Try: `pip3 install pg_analyse[cli]`

I've updated README to reflect that.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
