### ISSUE TITLE
To add global `schema` command-line argument

### ISSUE THREAD

**Issue by ba1dr** [idlesign/pg_analyse#2]
By default schema `public` used, isn't it?

As far as I can see it is possible to set custom schema for each inspection, but it would be better to have additional argument to set it.

Actually I'd prefer to see all schemas in the output.

**Comment by idlesign** [comment]
You can now pass common params to inspections using `common` keyword in arguments in `master`. Try it out.

With that I'm not sure introspecting all schemas at once is a common request.

**Comment by idlesign** [comment]
0.5.0 is out.
Considered closed. 
Thank your for the hint.
